uploads = []
outputs = []

[[generated]]
id = "fDJNMr6dpuH29OQamAkgh"
uri = "file://artifacts/oracle-preview-ritual/public/assets/palm.png"
type = "image"
title = "detailed palm photography"

[[generated]]
id = "EpqEbqH3NlDuhJZ5mXZtc"
uri = "file://artifacts/oracle-preview-ritual/public/images/palm.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QgrC5b-McCAaHuTBkaG39"
uri = "file://artifacts/oracle-preview-ritual/public/images/sigil.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MLJKVquoosBtNVmpNFous"
uri = "file://artifacts/oracle-preview-ritual/public/images/archetype-frame.png"
type = "image"
title = "generated_image"

[[generated]]
id = "C9OL24ik79iF-f8qsygTt"
uri = "file://artifacts/oracle-preview-ritual/public/images/deep-dive-cover.png"
type = "image"
title = "generated_image"
