// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/oracle-landing/EditorialColumn.tsx": () => import("../components/mockups/oracle-landing/EditorialColumn.tsx"),
  "./components/mockups/oracle-landing/HorizonSplit.tsx": () => import("../components/mockups/oracle-landing/HorizonSplit.tsx"),
  "./components/mockups/oracle-landing/OrbitalFloat.tsx": () => import("../components/mockups/oracle-landing/OrbitalFloat.tsx")
};
